export const warehousNvlData = [
  {
    time: "7:15",
    nha_cung_cap: "Mekong",
    ma_cuon_tbdx: "456",
    loai_giay: "BM",
    kho: "10",
    dinh_luong: "150",
    so_kg: "1800",
    vi_tri: "A01",
    nguoi_nhap: "BB",
  },
  {
    time: "9:00",
    nha_cung_cap: "Hansea",
    ma_cuon_tbdx: "785",
    loai_giay: "BM",
    kho: "10",
    dinh_luong: "400",
    so_kg: "2000",
    vi_tri: "C03",
    nguoi_nhap: "AA",
  },
  {
    time: "9:15",
    nha_cung_cap: "Hansea",
    ma_cuon_tbdx: "253",
    loai_giay: "BM",
    kho: "10",
    dinh_luong: "150",
    so_kg: "2000",
    vi_tri: "C03",
    nguoi_nhap: "AA",
  },
  {
    time: "",
    nha_cung_cap: "PK",
    ma_cuon_tbdx: "333",
    loai_giay: "BM",
    kho: "5",
    dinh_luong: "500",
    so_kg: "2000",
    vi_tri: "D01",
    nguoi_nhap: "",
  },
  {
    time: "",
    nha_cung_cap: "Shilla",
    ma_cuon_tbdx: "145",
    loai_giay: "BM",
    kho: "1",
    dinh_luong: "200",
    so_kg: "1500",
    vi_tri: "D02",
    nguoi_nhap: "",
  },
  {
    time: "",
    nha_cung_cap: "Simone",
    ma_cuon_tbdx: "158",
    loai_giay: "BM",
    kho: "2",
    dinh_luong: "200",
    so_kg: "2000",
    vi_tri: "D02",
    nguoi_nhap: "",
  },
];

export const warehousExportNVLData = [
  {
    time: "8:00",
    dau_may: "sC",
    ma_cuon_tbdx: "456",
    loai_giay: "BM",
    kho: "10",
    so_kg: "1800",
    vi_tri: "A01",
  },
  {
    time: "9:00",
    dau_may: "IC",
    ma_cuon_tbdx: "785",
    loai_giay: "BM",
    kho: "10",
    so_kg: "2000",
    vi_tri: "C03",
  },
  {
    time: "9:15",
    dau_may: "sB",
    ma_cuon_tbdx: "253",
    loai_giay: "BM",
    kho: "10",
    so_kg: "2000",
    vi_tri: "C03",
  },
  {
    time: "",
    dau_may: "IB",
    ma_cuon_tbdx: "333",
    loai_giay: "BM",
    kho: "5",
    so_kg: "2000",
    vi_tri: "D01",
  },
  {
    time: "",
    dau_may: "sE",
    ma_cuon_tbdx: "145",
    loai_giay: "BM",
    kho: "1",
    so_kg: "1500",
    vi_tri: "D02",
  },
  {
    time: "",
    dau_may: "IE",
    ma_cuon_tbdx: "158",
    loai_giay: "BM",
    kho: "2",
    dinh_luong: "200",
    so_kg: "2000",
    vi_tri: "D02",
    nguoi_xuat: "",
    thoi_gian_xuat: "",
  },
];

export const warehousTPData = [
  {
    so_pallet: "T300/3",
    so_lot: "S2301",
    vi_tri: "A01",
    so_mql: "10",
    so_luong: "150",
    so_don_hang: "13112018",
    khach_hang: "Mekong",
    tem_id: "BB",
  },
  {
    so_pallet: "T300/3",
    so_lot: "S2301",
    so_mql: "10",
    so_luong: "150",
    so_don_hang: "13112018",
    khach_hang: "Mekong",
    vi_tri: "C03",
    tem_id: "AA",
  },
  {
    so_pallet: "T300/3",
    so_lot: "S2301",
    so_mql: "10",
    so_luong: "150",
    so_don_hang: "13112018",
    khach_hang: "Mekong",
    vi_tri: "C03",
    tem_id: "AA",
  },
  {
    so_pallet: "T300/3",
    so_lot: "S2301",
    so_mql: "10",
    so_luong: "150",
    so_don_hang: "13112018",
    khach_hang: "Mekong",
    vi_tri: "D01",
    tem_id: "",
  },
  {
    so_pallet: "T300/3",
    so_lot: "S2301",
    so_mql: "10",
    so_luong: "150",
    so_don_hang: "13112018",
    khach_hang: "Mekong",
    vi_tri: "D02",
    tem_id: "",
  },
  {
    so_pallet: "T300/3",
    so_lot: "S2301",
    so_mql: "10",
    so_luong: "150",
    so_don_hang: "13112018",
    khach_hang: "Mekong",
    vi_tri: "D02",
    tem_id: "",
  },
];

export const warehousExportTPData = [
  {
    time: "7:15",
    vi_tri: "A01",
    so_luong: "150",
    khach_hang: "Mekong",
    lot_id: "S2301",
    tem_id: "BBB",
  },
  {
    time: "9:00",
    so_luong: "150",
    khach_hang: "Mekong",
    vi_tri: "C03",
    lot_id: "S2301",
    tem_id: "BBB",
  },
  {
    time: "9:15",
    so_luong: "150",
    khach_hang: "Mekong",
    vi_tri: "C03",
    lot_id: "S2301",
    tem_id: "BBB",
  },
  {
    time: "",
    so_luong: "150",
    khach_hang: "Mekong",
    vi_tri: "D01",
    lot_id: "S2301",
    tem_id: "BBB",
  },
  {
    time: "",
    so_luong: "150",
    khach_hang: "Mekong",
    vi_tri: "D02",
    lot_id: "S2301",
    tem_id: "BBB",
  },
  {
    time: "",
    so_luong: "150",
    khach_hang: "Mekong",
    vi_tri: "D02",
    lot_id: "S2301",
    tem_id: "BBB",
  },
];
