export const warehousNvlData = [
  {
    time: "7:15",
    nha_cung_cap: "Mekong",
    ma_cuon_tbdx: "456",
    loai_giay: "BM",
    kho: "10",
    dinh_luong: "150",
    so_kg: "1800",
    vi_tri: "A01",
    nguoi_nhap: "BB",
  },
  {
    time: "9:00",
    nha_cung_cap: "Hansea",
    ma_cuon_tbdx: "785",
    loai_giay: "BM",
    kho: "10",
    dinh_luong: "400",
    so_kg: "2000",
    vi_tri: "C03",
    nguoi_nhap: "AA",
  },
  {
    time: "9:15",
    nha_cung_cap: "Hansea",
    ma_cuon_tbdx: "253",
    loai_giay: "BM",
    kho: "10",
    dinh_luong: "150",
    so_kg: "2000",
    vi_tri: "C03",
    nguoi_nhap: "AA",
  },
  {
    time: "",
    nha_cung_cap: "PK",
    ma_cuon_tbdx: "333",
    loai_giay: "BM",
    kho: "5",
    dinh_luong: "500",
    so_kg: "2000",
    vi_tri: "D01",
    nguoi_nhap: "",
  },
  {
    time: "",
    nha_cung_cap: "Shilla",
    ma_cuon_tbdx: "145",
    loai_giay: "BM",
    kho: "1",
    dinh_luong: "200",
    so_kg: "1500",
    vi_tri: "D02",
    nguoi_nhap: "",
  },
  {
    time: "",
    nha_cung_cap: "Simone",
    ma_cuon_tbdx: "158",
    loai_giay: "BM",
    kho: "2",
    dinh_luong: "200",
    so_kg: "2000",
    vi_tri: "D02",
    nguoi_nhap: "",
  },
];
